apiVersion: v1
kind: Pod
metadata:
  name: test-fuse
  annotations:
    container.apparmor.security.beta.kubernetes.io/test-fuse: localhost/docker-fuse 
spec:
  restartPolicy: OnFailure
  imagePullSecrets:
  - name: registry-secret
  containers:
  - image: soolaugust/fuse-device-plugin:test-sshfs
    name: test-fuse 
    command:
      - /bin/bash
      - -c
      - |2-
        mkdir /mnt/test
        echo "root\n" | sshfs -o allow_other root@10.1.102.45:/home/wyq
        sleep 10000
    resources:
      limits:
        github.com/fuse: 1
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
